# .github/workflows/schedule_pipeline.yml

name: Run Daily News Pipeline

on:
  # 1. 수동으로 실행할 수 있도록 설정
  workflow_dispatch:
  
  # 2. 스케줄에 따라 자동 실행 설정
  schedule:
    # 매일 22:00 UTC (한국 시간 오전 7시)에 실행
    - cron: '0 22 * * *'

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests beautifulsoup4 lxml google-generativeai

      - name: Run Python Pipeline
        env:
          # GitHub Secrets에 저장된 값들을 환경 변수로 주입
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
          NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
          JSONBIN_API_KEY: ${{ secrets.JSONBIN_API_KEY }}
          JSONBIN_BIN_ID: ${{ secrets.JSONBIN_BIN_ID }}
        run: |
          python backend/run_pipeline.py